# https://taskfile.dev

version: '3'

tasks:
  lint:
    cmds:
      - terraform fmt -recursive

  init:
    cmds:
      - terraform -chdir=bootstrap init -upgrade
      - terraform -chdir=namespace-vending init -upgrade
      - terraform -chdir=namespace-root init -upgrade

  validate:
    deps: ["lint", "init"]
    cmds:
      - terraform -chdir=bootstrap validate
      - terraform -chdir=namespace-vending validate
      - terraform -chdir=namespace-root validate

  bootstrap:
    deps: ["lint"]
    dir: ./bootstrap
    dotenv: [".env"]
    cmds:
      - terraform init
      - terraform validate
      - terraform apply

  bootstrap-destroy:
    deps: ["lint"]
    dir: ./bootstrap
    dotenv: [".env"]
    cmds:
      - terraform validate
      - terraform destroy

  bootstrap-plan:
    deps: ["lint"]
    dir: ./bootstrap
    dotenv: [".env"]
    cmds:
      - terraform init
      - terraform plan

  bootstrap-refresh:
    deps: ["lint"]
    dir: ./bootstrap
    dotenv: [".env"]
    cmds:
      - terraform plan -refresh
