# https://taskfile.dev

version: '3'

dotenv: ['.env']

vars:
  TF_DIRS:
    sh: ls -d bootstrap namespace-* modules/*/ 2>/dev/null | xargs

tasks:
  lint:
    desc: Run all pre-commit hooks and format Vault policies
    cmds:
      - pre-commit run --all-files
      - ls policies/*.hcl | xargs -L1 vault policy fmt

  clean:
    desc: Remove all .terraform directories and lock files
    cmds:
      - find . -name ".terraform" -type d -prune -exec rm -rf {} +
      - find . -name ".terraform.lock.hcl" -type f -delete

  init:
    desc: Initialize Terraform (no backend) for all primary directories
    cmds:
      - for: { var: TF_DIRS }
        cmd: terraform -chdir={{.ITEM}} init -upgrade -backend=false

  validate:
    desc: Initialize and validate all Terraform configurations
    deps: [init]
    sources:
      - "{{.ITEM}}/*.tf"
      - "{{.ITEM}}/*.hcl"
    cmds:
      - for: { var: TF_DIRS }
        cmd: |
          echo "--> Validating: {{.ITEM}}"
          terraform -chdir={{.ITEM}} validate

  bootstrap:apply:
    desc: Apply bootstrap infrastructure
    dir: ./bootstrap
    preconditions:
      - &tfvars_precondition
        sh: test -f terraform.tfvars
        msg: "terraform.tfvars not found. Copy terraform.tfvars.example to terraform.tfvars."
    cmds:
      - terraform init
      - terraform apply -auto-approve
      - task: update-env

  bootstrap:destroy:
    desc: Destroy bootstrap infrastructure
    dir: ./bootstrap
    cmds:
      - terraform destroy

  bootstrap:destroy-vault:
    desc: Destroy only HCP Vault cluster resources (HVN, cluster, admin token)
    dir: ./bootstrap
    cmds:
      - terraform init
      - terraform destroy -target=hcp_vault_cluster.vault

  bootstrap:plan:
    desc: Plan bootstrap infrastructure changes
    dir: ./bootstrap
    preconditions:
      - *tfvars_precondition
    cmds:
      - terraform init
      - terraform plan

  bootstrap:refresh:
    desc: Refresh bootstrap state
    dir: ./bootstrap
    cmds:
      - terraform plan -refresh-only

  debug:
    desc: Debug variable evaluation
    cmds:
      - echo "TF_DIRS = {{.TF_DIRS}}"

  test-ci:
    desc: Run GitHub Actions locally using act (requires Docker)
    preconditions:
      - sh: command -v act >/dev/null 2>&1
        msg: "act is not installed. Install it with 'brew install act' or visit https://github.com/nektos/act"
    cmds:
      - task: clean
      - act --validate
      - act --container-architecture linux/amd64 -P ubuntu-latest=catthehacker/ubuntu:act-latest
      - task: clean

  vault:vars:
    aliases: [vars]
    desc: export vault environment variables (eval this output)
    vars:
      VAULT_ADDR:
        sh: terraform -chdir=bootstrap output -raw hcp_public_endpoint 2>/dev/null || echo ""
      VAULT_TOKEN:
        sh: terraform -chdir=bootstrap output -raw hcp_admin_token 2>/dev/null || echo ""
      VAULT_NAMESPACE:
        sh: terraform -chdir=bootstrap output -raw namespace 2>/dev/null || echo "admin"
    cmds:
      - |
        if [ -z "{{.VAULT_ADDR}}" ] || [ -z "{{.VAULT_TOKEN}}" ]; then
          echo "Error: Vault configuration not found. Run 'task bootstrap:apply' first." >&2
          exit 1
        fi
        echo "export VAULT_ADDR='{{.VAULT_ADDR}}'"
        echo "export VAULT_TOKEN='{{.VAULT_TOKEN}}'"
        echo "export VAULT_NAMESPACE='{{.VAULT_NAMESPACE}}'"
        echo ""
        echo "# Run the following to set environment variables:"
        echo "# eval \"\$(task vault:vars)\""
    silent: true

  vault:status:
    desc: Check Vault status
    cmds:
      - vault status

  vault:ui:
    desc: Open Vault UI in the browser and copy token to clipboard
    aliases: [ui]
    cmds:
      - echo -n $VAULT_TOKEN | pbcopy
      - open $VAULT_ADDR

  update-env:
    desc: Update .env file from Terraform outputs
    cmds:
      - ./scripts/update_env.sh
    silent: true
