# https://taskfile.dev

version: '3'

tasks:
  lint:
    cmds:
      - pre-commit run --all-files

  init:
    cmds:
      - terraform -chdir=bootstrap init -upgrade
      - terraform -chdir=namespace-vending init -upgrade
      - terraform -chdir=namespace-root init -upgrade

  validate:
    deps: ["lint", "init"]
    cmds:
      - terraform -chdir=bootstrap validate
      - terraform -chdir=namespace-vending validate
      - terraform -chdir=namespace-root validate

  bootstrap-apply:
    deps: ["lint"]
    dir: ./bootstrap
    dotenv: [".env"]
    preconditions:
      - sh: test -f terraform.tfvars
        msg: "terraform.tfvars not found. Copy terraform.tfvars.example to terraform.tfvars and configure your values."
    cmds:
      - terraform init
      - terraform validate
      - terraform apply -auto-approve

  bootstrap-destroy:
    deps: ["lint"]
    dir: ./bootstrap
    dotenv: [".env"]
    cmds:
      - terraform validate
      - terraform destroy

  bootstrap-plan:
    deps: ["lint"]
    dir: ./bootstrap
    dotenv: [".env"]
    preconditions:
      - sh: test -f terraform.tfvars
        msg: "terraform.tfvars not found. Copy terraform.tfvars.example to terraform.tfvars and configure your values."
    cmds:
      - terraform init
      - terraform plan

  bootstrap-refresh:
    deps: ["lint"]
    dir: ./bootstrap
    dotenv: [".env"]
    cmds:
      - terraform plan -refresh

  vault:vars:
    aliases: [vars]
    dir: ./bootstrap
    cmds:
      - echo "export VAULT_ADDR=$(terraform output -raw hcp_public_endpoint)"
      - echo "export VAULT_TOKEN=$(terraform output -raw hcp_admin_token)"
      - echo "export VAULT_NAMESPACE=admin"
    silent: true
