# https://taskfile.dev

version: '3'

tasks:
  lint:
    cmds:
      - terraform fmt -recursive

  bootstrap:
    deps: ["lint"]
    dir: ./bootstrap
    dotenv: [".env"]
    cmds:
      - terraform init
      - terraform validate
      - terraform apply

  bootstrap-destroy:
    deps: ["lint"]
    dir: ./bootstrap
    dotenv: [".env"]
    cmds:
      - terraform validate
      - terraform destroy

  bootstrap-plan:
    deps: ["lint"]
    dir: ./bootstrap
    dotenv: [".env"]
    cmds:
      - terraform init
      - terraform plan

  bootstrap-refresh:
    deps: ["lint"]
    dir: ./bootstrap
    dotenv: [".env"]
    cmds:
      - terraform plan -refresh
