#!/usr/bin/env bash
set -euo pipefail

# Script: update_env.sh
# Purpose: Generate/update .env file using variables from environment

ENV_FILE=".env"

if [ -z "${VAULT_ADDR:-}" ]; then
  echo "Error: VAULT_ADDR is not set. Has Terraform been applied in bootstrap?"
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# Vault CLI Environment Variables
# Auto-generated by: Taskfile + scripts/update_env.sh
# Generated at: $(date)

# Vault server address
export VAULT_ADDR='$VAULT_ADDR'

# Vault authentication token
export VAULT_TOKEN='$VAULT_TOKEN'

# Vault namespace
export VAULT_NAMESPACE='${VAULT_NAMESPACE:-admin}'

# Usage:
# 1. Load variables: source .env
# 2. Verify: echo \$VAULT_ADDR
# 3. Test connection: vault status
EOF

echo "✓ .env file updated with VAULT_ADDR, VAULT_TOKEN, and VAULT_NAMESPACE"
