#!/usr/bin/env bash
set -euo pipefail

# Script: update_env.sh
# Purpose: Generate/update .env file using variables from Terraform outputs

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"

echo "Fetching latest Vault configuration from Terraform..."

# Force fetch from terraform outputs to ensure we sync with actual state
# We ignore environment variables here to avoid stale data persistence
VAULT_ADDR=$(terraform -chdir="$PROJECT_ROOT/bootstrap" output -raw hcp_public_endpoint 2>/dev/null || echo "")
VAULT_TOKEN=$(terraform -chdir="$PROJECT_ROOT/bootstrap" output -raw hcp_admin_token 2>/dev/null || echo "")
VAULT_NAMESPACE=$(terraform -chdir="$PROJECT_ROOT/bootstrap" output -raw namespace 2>/dev/null || echo "admin")

if [ -z "$VAULT_ADDR" ] || [ -z "$VAULT_TOKEN" ]; then
  echo "Error: Could not fetch Vault configuration. Has 'task bootstrap:apply' been run?"
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# Vault CLI Environment Variables
# Auto-generated by: scripts/update_env.sh
# Generated at: $(date)

export VAULT_ADDR='$VAULT_ADDR'
export VAULT_TOKEN='$VAULT_TOKEN'
export VAULT_NAMESPACE='$VAULT_NAMESPACE'

# Usage:
# 1. Load variables: source .env
# 2. Verify: echo \$VAULT_ADDR
# 3. Test connection: vault status
EOF

echo "✓ .env file updated with latest values from Terraform."
